# GitLab CI pipeline for BlockPanel (mirrored from GitHub)
# Provides: backend tests, frontend build, multi-arch Docker image build & push (Docker Hub + optional GitLab registry), Trivy scan.
# Adjust runner tags / image versions as needed.

stages:
  - test
  - build
  - scan
  - release

# Global variables for docker:dind multi-arch builds
variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  # Increase log limit if needed
  FF_NETWORK_PER_BUILD: "true"
  # Optionally set APP_NAME propagated into images
  APP_NAME: "BlockPanel"

# Cache directories (node modules, pip)
cache:
  paths:
    - frontend/node_modules/
    - .cache/pip
  key: "$CI_COMMIT_REF_SLUG"
  policy: pull-push

.backend_tests:
  stage: test
  image: python:3.11-slim
  services:
    - name: postgres:15-alpine
      alias: postgres
  variables:
    POSTGRES_PASSWORD: postgres123
    POSTGRES_DB: minecraft_controller_test
    POSTGRES_USER: postgres
    DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/minecraft_controller_test
    USE_POSTGRES: "true"
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r backend/requirements.txt
  script:
    - python -m py_compile backend/*.py
    - python test_complete_system.py
  artifacts:
    when: always
    reports:
      junit: junit-backend.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_TAG

frontend_tests:
  stage: test
  image: node:20-alpine
  before_script:
    - |
      cd frontend
      if [ -f package-lock.json ]; then
        echo "Using npm ci (lockfile present)"
        npm ci
      else
        echo "No package-lock.json found – using npm install"
        npm install --no-audit --no-fund
      fi
  script:
    - npm run build
  artifacts:
    paths:
      - frontend/build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_TAG

backend_tests:
  extends: .backend_tests
  variables:
    SKIP_FRONTEND_CHECK: "true"

# Build & push multi-arch images using buildx; requires privileged runner (shared GitLab runners generally allow this with docker:dind)
build_images:
  stage: build
  image: docker:24.0.9
  services:
    - docker:24.0.9-dind
  needs: [backend_tests, frontend_tests]
  variables:
    # Provide DOCKERHUB_USERNAME / DOCKERHUB_TOKEN in GitLab CI/CD variables for Docker Hub push
    # Optionally set GITLAB_PUSH="true" to also push to GitLab registry
    DOCKER_CLI_EXPERIMENTAL: "enabled"
  before_script:
    - apk add --no-cache bash curl git
    - |
      if [ -n "$DOCKERHUB_USERNAME" ] && [ -n "$DOCKERHUB_TOKEN" ]; then
        echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        DOCKER_PUSH_OK=1
      else
        echo "Docker Hub credentials not set – skipping image build & push (will still allow release job)."
        DOCKER_PUSH_OK=0
      fi
    - |
      if [ "${GITLAB_PUSH}" = "true" ]; then
        echo "Logging into GitLab Container Registry ${CI_REGISTRY}"
        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
      else
        echo "Skipping GitLab registry login (GITLAB_PUSH != true)"
      fi
    - docker run --privileged --rm tonistiigi/binfmt --install all
    - docker buildx create --name bpbuilder --use || docker buildx use bpbuilder
    - docker buildx inspect --bootstrap
  script:
    - |
      if [ "$DOCKER_PUSH_OK" -ne 1 ]; then
        echo "Skipping multi-arch image build because credentials are missing."
        exit 0
      fi
      SHORT_SHA=${CI_COMMIT_SHORT_SHA}
      DATE_TAG=$(date -u +%Y%m%d)
      VERSION_TAG=""; IS_RELEASE="false"
      if [[ -n "$CI_COMMIT_TAG" && "$CI_COMMIT_TAG" == v* ]]; then
        VERSION_TAG=$CI_COMMIT_TAG
        IS_RELEASE="true"
      fi
      echo "Building images (short=$SHORT_SHA date=$DATE_TAG release=$IS_RELEASE tag=$VERSION_TAG)"
      # Prepare GitLab image base if pushing
      if [[ "$GITLAB_PUSH" == "true" ]]; then
        GL_BASE="$CI_REGISTRY_IMAGE"
      else
        GL_BASE=""
      fi
      # Runtime image tags
      RUNTIME_TAGS="-t $DOCKERHUB_USERNAME/blockpanel-runtime:latest -t $DOCKERHUB_USERNAME/blockpanel-runtime:$SHORT_SHA -t $DOCKERHUB_USERNAME/blockpanel-runtime:$DATE_TAG"
      if [[ $IS_RELEASE == "true" ]]; then RUNTIME_TAGS+=" -t $DOCKERHUB_USERNAME/blockpanel-runtime:$VERSION_TAG"; fi
      if [[ -n "$GL_BASE" ]]; then
        RUNTIME_TAGS+=" -t ${GL_BASE}/blockpanel-runtime:latest -t ${GL_BASE}/blockpanel-runtime:$SHORT_SHA -t ${GL_BASE}/blockpanel-runtime:$DATE_TAG"
        if [[ $IS_RELEASE == "true" ]]; then RUNTIME_TAGS+=" -t ${GL_BASE}/blockpanel-runtime:$VERSION_TAG"; fi
      fi
      # Controller image tags
      CTRL_TAGS="-t $DOCKERHUB_USERNAME/blockpanel:latest -t $DOCKERHUB_USERNAME/blockpanel:$SHORT_SHA -t $DOCKERHUB_USERNAME/blockpanel:$DATE_TAG"
      if [[ $IS_RELEASE == "true" ]]; then CTRL_TAGS+=" -t $DOCKERHUB_USERNAME/blockpanel:$VERSION_TAG"; fi
      if [[ -n "$GL_BASE" ]]; then
        CTRL_TAGS+=" -t ${GL_BASE}/blockpanel:latest -t ${GL_BASE}/blockpanel:$SHORT_SHA -t ${GL_BASE}/blockpanel:$DATE_TAG"
        if [[ $IS_RELEASE == "true" ]]; then CTRL_TAGS+=" -t ${GL_BASE}/blockpanel:$VERSION_TAG"; fi
      fi
      echo "Runtime build tags: $RUNTIME_TAGS"
      echo "Controller build tags: $CTRL_TAGS"
      # Build & push runtime (multi-arch) with all tags
      docker buildx build --platform linux/amd64,linux/arm64 -f docker/runtime.Dockerfile $RUNTIME_TAGS --push .
      # Build & push controller (multi-arch) with all tags
      docker buildx build --platform linux/amd64,linux/arm64 -f docker/controller.Dockerfile $CTRL_TAGS --push .
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_COMMIT_TAG

trivy_scan:
  stage: scan
  image: aquasec/trivy:latest
  needs: [build_images]
  script:
      cd frontend
      if [ -f package-lock.json ]; then
    paths:
      - trivy-results.sarif
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_COMMIT_TAG

release_summary:
  stage: release
    - |
      cd frontend
      npm run build
  image: alpine:3.20
  script:
    - echo "Images pushed to Docker Hub under $DOCKERHUB_USERNAME"
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        echo "Tag: $CI_COMMIT_TAG";
      else
        echo "Tag: (not version tag)";
      fi
  rules:
    - if: $CI_COMMIT_TAG

gitlab_release:
  stage: release
  needs: [build_images]
  image: alpine:3.20
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Preparing GitLab release for $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    name: "BlockPanel $CI_COMMIT_TAG"
    description: |
      Automated release generated by GitLab CI.

      Docker Hub Images:
      - moresonsun/blockpanel:$CI_COMMIT_TAG
      - moresonsun/blockpanel-runtime:$CI_COMMIT_TAG

      Quick install (Linux/macOS):
      ```bash
      curl -fsSL https://raw.githubusercontent.com/moresonsunn/minecraft-server/$CI_COMMIT_TAG/install.sh | bash -s -- -v $CI_COMMIT_TAG
      ```

      Quick install (Windows PowerShell):
      ```powershell
      irm https://raw.githubusercontent.com/moresonsunn/minecraft-server/$CI_COMMIT_TAG/install.ps1 | iex -v $CI_COMMIT_TAG
      ```
    assets:
      links:
        - name: install.sh
          url: "$CI_PROJECT_URL/-/raw/$CI_COMMIT_TAG/install.sh"
        - name: install.ps1
          url: "$CI_PROJECT_URL/-/raw/$CI_COMMIT_TAG/install.ps1"
        - name: docker-compose.yml
          url: "$CI_PROJECT_URL/-/raw/$CI_COMMIT_TAG/docker-compose.yml"

# Notes:
# 1. Add CI/CD variables in GitLab project settings:
#    - DOCKERHUB_USERNAME
#    - DOCKERHUB_TOKEN (Docker Hub access token)
# 2. Optional: GITLAB_PUSH=true to re-tag image into GitLab registry (single-arch retag approach shown; multi-arch mirror could be scripted with crane/skopeo if needed).
# 3. Pushing a git tag starting with v (e.g. v0.1.2) triggers release tagging similar to GitHub workflow.
