version: "3.9"
services:
  controller:
    build:
      context: .
      dockerfile: docker/controller.Dockerfile
    image: mc-controller:latest
    ports:
      - "8000:8000"
    volumes:
      - mc_servers_data:/data/servers
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SERVERS_CONTAINER_ROOT=/data/servers
      - SERVERS_VOLUME_NAME=minecraft-server_mc_servers_data
    restart: unless-stopped

volumes:
  mc_servers_data:
